<h1 style="color:orange; text-align:center; font-size:40px;">Numpy Intro</h1>

In [1]:
import numpy as np
import sys

In [2]:
arr = np.array([5,1,7,9,3])
arr

array([5, 1, 7, 9, 3])

In [3]:
type(arr)

numpy.ndarray

---
# Benefit of Numpy Array Over Python List
---

In [4]:
numbers = list(range(1,101))
numbers[:5]

[1, 2, 3, 4, 5]

In [5]:
print(f"Size of single element in list = {sys.getsizeof(numbers[0])} bytes") 

Size of single element in list = 28 bytes


In [6]:
print(f"Size of entire list = {sys.getsizeof(numbers[0]) * len(numbers)} bytes") 

Size of entire list = 2800 bytes


# Numpy Array As Space Efficient

**Using Numpy Array**

In [7]:
arr = np.arange(1,101,dtype = "int8")
arr[:5]

array([1, 2, 3, 4, 5], dtype=int8)

In [8]:
print(f"Size of single element in numpy array is = {arr[0].nbytes} bytes") 

Size of single element in numpy array is = 1 bytes


In [9]:
print(f"Size of entire numpy array is = {arr.nbytes} bytes") 

Size of entire numpy array is = 100 bytes


In [10]:
arr.dtype

dtype('int8')

# Numpy Array As Time Efficient

**I will create 2 arrays of size 10M 10000000 later on we will sum both arrays**

In [11]:
import time

In [33]:
list1 = list(range(1,10000001))
list2 = list(range(1,10000001))
print(f"List 1 = {list1[:5]}")
print(f"List 2 = {list2[:5]}")
# print(list1)

List 1 = [1, 2, 3, 4, 5]
List 2 = [1, 2, 3, 4, 5]


In [28]:
list3 = []
start_time = time.time()
for i in range(10000000):
    list3.append(list1[i]+list2[i])

end_time = time.time()
print(f"List 3 = {list3[:5]}")
print(f"Time taken to add 2 python list is {end_time - start_time} secs")

List 3 = [2, 4, 6, 8, 10]
Time taken to add 2 python list is 2.2630913257598877 secs


In [31]:
# Using Numpy
arr1 = np.arange(1,10000001, dtype="int32")
arr2 = np.arange(1,10000001)
print(f"Array 1 = {arr1[:5]}")
print(f"Array 2 = {arr2[:5]}")
print(arr1)

Array 1 = [1 2 3 4 5]
Array 2 = [1 2 3 4 5]
[       1        2        3 ...  9999998  9999999 10000000]


In [30]:
start_time = time.time()
arr3 = arr1 + arr2
end_time = time.time()
print(f"Array 3 = {arr3[:5]}")
print(f"Time taken to add 2 numpy array is {end_time - start_time} secs")

Array 3 = [ 2  4  6  8 10]
Time taken to add 2 numpy array is 0.07260727882385254 secs
