In [1]:
import numpy as np

In [2]:
arr = np.array([5,1,7,9,3])
arr

array([5, 1, 7, 9, 3])

In [3]:
arr.ndim

1

In [4]:
print(arr)

[5 1 7 9 3]


In [5]:
arr = np.array(
    [
        [5,10,20],
        [3,15,9],
        [6,8,6],
        [12,4,6]
    ], dtype = 'int8'
)
arr

array([[ 5, 10, 20],
       [ 3, 15,  9],
       [ 6,  8,  6],
       [12,  4,  6]], dtype=int8)

In [6]:
arr.ndim

2

In [7]:
arr[1][2]

np.int8(9)

In [8]:
arr[1,2]

np.int8(9)

In [9]:
arr[1,2] = 80

In [10]:
arr

array([[ 5, 10, 20],
       [ 3, 15, 80],
       [ 6,  8,  6],
       [12,  4,  6]], dtype=int8)

In [11]:
arr.shape

(4, 3)

In [12]:
print(f"{arr.itemsize} bytes")

1 bytes


In [13]:
arr.nbytes

12

In [14]:
arr.size

12

In [15]:
np.sort(arr)

array([[ 5, 10, 20],
       [ 3, 15, 80],
       [ 6,  6,  8],
       [ 4,  6, 12]], dtype=int8)

In [16]:
arr

array([[ 5, 10, 20],
       [ 3, 15, 80],
       [ 6,  8,  6],
       [12,  4,  6]], dtype=int8)

In [17]:
np.sort(arr,0)

array([[ 3,  4,  6],
       [ 5,  8,  6],
       [ 6, 10, 20],
       [12, 15, 80]], dtype=int8)

In [18]:
np.sort(arr, None)

array([ 3,  4,  5,  6,  6,  6,  8, 10, 12, 15, 20, 80], dtype=int8)

In [19]:
arr

array([[ 5, 10, 20],
       [ 3, 15, 80],
       [ 6,  8,  6],
       [12,  4,  6]], dtype=int8)

In [20]:
arr.reshape(3,4)

array([[ 5, 10, 20,  3],
       [15, 80,  6,  8],
       [ 6, 12,  4,  6]], dtype=int8)

In [21]:
arr

array([[ 5, 10, 20],
       [ 3, 15, 80],
       [ 6,  8,  6],
       [12,  4,  6]], dtype=int8)

In [22]:
flat_arr_1 = arr.flatten()

In [23]:
flat_arr_1

array([ 5, 10, 20,  3, 15, 80,  6,  8,  6, 12,  4,  6], dtype=int8)

In [24]:
flat_arr_1[5] = -6

In [25]:
flat_arr_1

array([ 5, 10, 20,  3, 15, -6,  6,  8,  6, 12,  4,  6], dtype=int8)

In [26]:
arr

array([[ 5, 10, 20],
       [ 3, 15, 80],
       [ 6,  8,  6],
       [12,  4,  6]], dtype=int8)

In [27]:
flat_arr_2 = arr.ravel()

In [28]:
flat_arr_2

array([ 5, 10, 20,  3, 15, 80,  6,  8,  6, 12,  4,  6], dtype=int8)

In [29]:
flat_arr_2[5] = -52

In [30]:
flat_arr_2

array([  5,  10,  20,   3,  15, -52,   6,   8,   6,  12,   4,   6],
      dtype=int8)

In [31]:
arr

array([[  5,  10,  20],
       [  3,  15, -52],
       [  6,   8,   6],
       [ 12,   4,   6]], dtype=int8)

In [32]:
arr[2,2] = 65

In [33]:
arr

array([[  5,  10,  20],
       [  3,  15, -52],
       [  6,   8,  65],
       [ 12,   4,   6]], dtype=int8)

In [34]:
flat_arr_2

array([  5,  10,  20,   3,  15, -52,   6,   8,  65,  12,   4,   6],
      dtype=int8)

In [35]:
flat_arr_1.size

12

In [36]:
flat_arr_1.reshape(2,6)

array([[ 5, 10, 20,  3, 15, -6],
       [ 6,  8,  6, 12,  4,  6]], dtype=int8)

In [37]:
flat_arr_1

array([ 5, 10, 20,  3, 15, -6,  6,  8,  6, 12,  4,  6], dtype=int8)

In [38]:
flat_arr_2.reshape(6,2)

array([[  5,  10],
       [ 20,   3],
       [ 15, -52],
       [  6,   8],
       [ 65,  12],
       [  4,   6]], dtype=int8)

In [39]:
arr

array([[  5,  10,  20],
       [  3,  15, -52],
       [  6,   8,  65],
       [ 12,   4,   6]], dtype=int8)

In [40]:
flat_arr_2

array([  5,  10,  20,   3,  15, -52,   6,   8,  65,  12,   4,   6],
      dtype=int8)

In [41]:
np.linspace(10,20)

array([10.        , 10.20408163, 10.40816327, 10.6122449 , 10.81632653,
       11.02040816, 11.2244898 , 11.42857143, 11.63265306, 11.83673469,
       12.04081633, 12.24489796, 12.44897959, 12.65306122, 12.85714286,
       13.06122449, 13.26530612, 13.46938776, 13.67346939, 13.87755102,
       14.08163265, 14.28571429, 14.48979592, 14.69387755, 14.89795918,
       15.10204082, 15.30612245, 15.51020408, 15.71428571, 15.91836735,
       16.12244898, 16.32653061, 16.53061224, 16.73469388, 16.93877551,
       17.14285714, 17.34693878, 17.55102041, 17.75510204, 17.95918367,
       18.16326531, 18.36734694, 18.57142857, 18.7755102 , 18.97959184,
       19.18367347, 19.3877551 , 19.59183673, 19.79591837, 20.        ])

In [43]:
np.linspace(10,20,9)

array([10.  , 11.25, 12.5 , 13.75, 15.  , 16.25, 17.5 , 18.75, 20.  ])

In [44]:
np.linspace(10,20,5)

array([10. , 12.5, 15. , 17.5, 20. ])

In [45]:
np.linspace(10,100,10)

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [46]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [47]:
np.zeros((3,4),'int64')

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [48]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [49]:
arr

array([[  5,  10,  20],
       [  3,  15, -52],
       [  6,   8,  65],
       [ 12,   4,   6]], dtype=int8)

In [50]:
arr.sum()

np.int64(102)

In [53]:
for row in arr:
    print(row)

[ 5 10 20]
[  3  15 -52]
[ 6  8 65]
[12  4  6]


In [54]:
for row in arr:
    for column in row:
        print(column , end=" ")
    print()

5 10 20 
3 15 -52 
6 8 65 
12 4 6 


In [56]:
arr

array([[  5,  10,  20],
       [  3,  15, -52],
       [  6,   8,  65],
       [ 12,   4,   6]], dtype=int8)

In [59]:
arr.sum(0)

array([26, 37, 39])

In [58]:
arr.sum(0).reshape(3,1)

array([[26],
       [37],
       [39]])

In [57]:
arr.sum(1)

array([ 35, -34,  79,  22])

In [60]:
arr.min()

np.int8(-52)

In [62]:
arr

array([[  5,  10,  20],
       [  3,  15, -52],
       [  6,   8,  65],
       [ 12,   4,   6]], dtype=int8)

In [61]:
arr.min(1)

array([  5, -52,   6,   4], dtype=int8)

In [63]:
arr.min(0)

array([  3,   4, -52], dtype=int8)

In [64]:
arr = np.array([81,16,25,20])
arr

array([81, 16, 25, 20])

In [65]:
np.sqrt(arr)

array([9.        , 4.        , 5.        , 4.47213595])

In [66]:
np.cbrt(arr)

array([4.32674871, 2.5198421 , 2.92401774, 2.71441762])

In [67]:
np.std(arr)

np.float64(26.462237244798484)